# Generated by Django 4.2.7 on 2024-07-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_usename',
            new_name='sender_username',
        ),
    ]
