# Generated by Django 4.2.7 on 2024-07-23 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0002_rename_sender_usename_message_sender_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='payment_id',
            new_name='loan_id',
        ),
    ]
