# Generated by Django 4.2.7 on 2024-07-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0003_rename_payment_id_loan_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='borrower_no',
            field=models.CharField(default='Null', help_text='Enter Borrower Number:', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower_no',
            field=models.CharField(default='Null', help_text='Enter Borrower Number:', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_no',
            field=models.CharField(blank=True, help_text='Enter the Payment Number', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_no',
            field=models.CharField(blank=True, help_text='Enter the Payment Number', max_length=30),
        ),
    ]
