# Generated by Django 4.2.7 on 2024-07-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0004_disbursement_borrower_no_loan_borrower_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='loan_duration_months',
            field=models.IntegerField(default=12, help_text='Loan Duration in Months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='lender_no',
            field=models.CharField(default='Null', help_text='Enter Lender Number:', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default='2024-01-01', help_text='Enter Date of last Payment'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_interest',
            field=models.DecimalField(decimal_places=2, default=1.2, help_text='Total Amount', max_digits=15),
            preserve_default=False,
        ),
    ]
