# Generated by Django 4.2.7 on 2024-07-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0005_disbursement_loan_duration_months_loan_lender_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_interest',
            field=models.DecimalField(decimal_places=2, help_text='Interest Rate', max_digits=15),
        ),
    ]
