# Generated by Django 4.2.7 on 2024-08-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0006_alter_loan_loan_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loanee',
            fields=[
                ('loanee_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('borrower_no', models.CharField(help_text='Enter the Transaction Number', max_length=30)),
                ('approved', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', help_text='Is borrower approved', max_length=3)),
            ],
        ),
    ]
