# Generated by Django 4.2.7 on 2024-08-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0007_loanee'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanee',
            name='applied',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Does borrower has an hanging application', max_length=3),
        ),
    ]
